fruits=[]
f1=input("Enter a name of a fruit\n")
f2=input("Enter a name of another fruit\n")
f3=input("Enter a name of another fruit\n")
f4=input("Enter a name of another fruit\n")
f5=input("Enter a name of another fruit\n")
f6=input("Enter a name of another fruit\n")
f7=input("Enter a name of another fruit\n")
fruits.append(f1)
fruits.append(f2)
fruits.append(f3)
fruits.append(f4)
fruits.append(f5)
fruits.append(f6)
fruits.append(f7)
print(fruits)
